### ISSUE TITLE
最新のドキュメントを取り込む

### ISSUE THREAD

**Issue by stc1988** [Moddable-OpenSource/moddable-jp#12]
[Moddable本体](https://github.com/Moddable-OpenSource/moddable)のリポジトリでドキュメントが修正・追加された時のフローを検討したいです。

実際に作業をしてみないと分からない部分がありますが、以下に検討事項を記載します

* 翻訳前のドキュメントないし新規追加ドキュメントについては、本リポジトリを本体リポジトリとSync?することで最新化できるのか
  * どのタイミングで最新化するのか
  * ドキュメント(*.md)が更新されたことを検知する仕組みが必要か
*  翻訳済みドキュメントは本体リポジトリと取り込み時にコンフリクトが起きるはずなので、そこで差分を翻訳してコンフリクトを解消するのか
   * コンフリクト量が多いと最新化作業のコストが高くなるので、頻度は空けすぎない方がよいか

**Comment by meganetaaan** [comment]
下記のようなフローを想定しています。

- Moddable本体の月次リリース毎にマージ作業を行う
- dev/translate-jpブランチからマージ用のブランチ（merge/v4.6.0 など）を切る
- Moddable本体のpublicブランチ（リリースタグのついたコミット）をマージ用ブランチにマージする
  - 翻訳済みドキュメントに差分がある場合: コンフリクトの形で現れるので、該当箇所を改めて翻訳する
  - 翻訳済みドキュメントに差分が無い場合: そのままfast-forwardでマージできるはず
- マージ用のブランチからdev/translate-jpに対してPRを作成する
- レビュー＆マージする

まずは月に1回でやってみて、1回のマージにかかる負担を様子見したいと思います。
もうすぐ5月分の月次リリースが来ると思うので↑で試してみましょうか。

**Comment by stc1988** [comment]
５月リリースをお試しで提案いただいたフローで問題ないです。
確か #11 でリンク先を修正したぐらいがコンフリクトするはずです。

**Comment by stc1988** [comment]
[Moddable SDK 4.7.0](https://github.com/Moddable-OpenSource/moddable/releases/tag/4.7.0)がリリースされたので、取り込みをお願い出来ますでしょうか

**Comment by stc1988** [comment]
#25 にて最新の取り込み済み。
[translation_readme.md](https://github.com/stc1988/moddable-jp/blob/dev/translate-jp/translation_readme.md#%E5%85%AC%E5%BC%8F%E3%83%AA%E3%83%9D%E3%82%B8%E3%83%88%E3%83%AA%E3%81%AE%E6%9B%B4%E6%96%B0%E3%81%AB%E8%BF%BD%E5%BE%93%E3%81%99%E3%82%8B)記載の手順ともズレもなかったため、最新のドキュメント取り込み方法としては問題は無さそうなので、本件はクローズします
