### ISSUE TITLE
readme for translation effort

### ISSUE THREAD

**Issue by phoddie** [Moddable-OpenSource/moddable-jp#2]
It is exciting to see this project get started!

I think it would be helpful to provide a document on this repository that introduces this translation project and how to get involved. Here is some information that would be helpful:

- Goals
- Basic approach
- How to get involved
- Contributing (PR & CLA)
- Link to discord server for team discussion
- Help needed (translating, reviewing, etc)

It could begin as a short document that grows in time as needed.

**Comment by meganetaaan** [comment]
Thank you for your suggestion. I agree that providing a document introducing the project's key points would be very helpful. I will work on creating this and adding it to the top of the repository. Using a separate markdown file linked from the `moddable-jp/readme.md` would be a good approach.

**Comment by meganetaaan** [comment]
I have created a PR at https://github.com/Moddable-OpenSource/moddable-jp/pull/5

Could you please add "reviewer" permission for @stc1988?

I may also request additional permissions for other volunteer developers later on.

**Comment by phoddie** [comment]
> I have created a PR at #5

Looks great. ;)

> Could you please add "reviewer" permission for @stc1988?

I added @stc1988 in the "triage" role. I think this is what is needed? It is easy to change, if necessary.

> I may also request additional permissions for other volunteer developers later on.

No problem.

**Comment by meganetaaan** [comment]
https://github.com/Moddable-OpenSource/moddable-jp/pull/5 merged!
I've also created [a new issue to](https://github.com/Moddable-OpenSource/moddable-jp/issues/3) share and manage the translation progress.

>I added @stc1988 in the "triage" role. I think this is what is needed? It is easy to change, if necessary.

This works perfectly. I can now make a review request to stc1988. Thank you for setting that up!

@mshioji has also volunteered to be a reviewer. Could you please assign them the same role as well?

**Comment by phoddie** [comment]
Glad that worked for @stc1988. I've added @mshioji in the Triage role, as requested.

> I've also created https://github.com/Moddable-OpenSource/moddable-jp/issues/3 share and manage the translation progress.

That's a long list. Good luck. ;)
