### ISSUE TITLE
機械翻訳ツールの案内を掲載する

### ISSUE THREAD

**Issue by meganetaaan** [Moddable-OpenSource/moddable-jp#6]
機械翻訳ツールの案内を掲載したいです。

[Reactのドキュメント日本語訳リポジトリ](https://github.com/reactjs/ja.react.dev/wiki#%E8%87%AA%E5%8B%95%E7%BF%BB%E8%A8%B3)では[ChatGPT Markdown Translator](https://github.com/reactjs/ja.react.dev/wiki#%E8%87%AA%E5%8B%95%E7%BF%BB%E8%A8%B3)を使った自動翻訳の方法が紹介されています。一方、ツールの精度には限界もあり、出力された文書を必ず自身でチェックするというルールも明記されています。私が最初に翻訳したREADMEも同ツールを使って翻訳しましたが、非常に便利だったので、このリポジトリでも取り入れて行きたいと思います。

具体的には、wikiまたはリポジトリの翻訳作業READMEに下記を追加します。

- 機械翻訳を使った手法を紹介する
- 具体的なツール、ここでは`ChatGPT Markdown Translator`のリンクと設定ファイルのサンプルを掲載する
- 「機械翻訳の結果を自身で全文チェックすること」というルールを明記する

**Comment by stc1988** [comment]
#7  を対応頂いたので本件はクローズできます
